### ISSUE TITLE
Can't seem to build the package

### ISSUE THREAD

**Issue by aunicorn111** [Torxed/archoffline#5] opened 2023-02-27 15:02 UTC
Not sure if I should post it here or rather on archwiki itself, but
The package cant seem to build and I have no idea why.

**Comment by aunicorn111** [comment] 2023-02-27 15:04
heres the output when i try to build the package 
**Making package: archiso-offline-releng 0.0.1.r1-1 (Mon 27 Feb 2023 02:57:31 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found archiso-offline-releng.tar.gz
==> Validating source files with sha256sums...
    archiso-offline-releng.tar.gz ... Skipped
==> Extracting sources...
  -> Extracting archiso-offline-releng.tar.gz with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
0
?
?
?
0
==> ERROR: A failure occurred in build().
    Aborting...**

**Comment by Torxed** [comment] 2023-02-27 23:13
I'll take a look in a few hours! :)

**Comment by aunicorn111** [comment] 2023-02-28 03:33
okay. Thanks!

**Comment by aunicorn111** [comment] 2023-02-28 04:00
I've tried to manually install all the dependencies first
And got a different outcome. This time it says
_==> Validating source files with sha256sums...
    archiso-offline-releng.tar.gz ... Skipped
==> Extracting sources...
  -> Extracting archiso-offline-releng.tar.gz with bsdtar
==> Starting prepare()...
==> Starting build()...
**/tmp/archiso-offline/archiso-offline-releng/src/usr/share/archiso/configs/offline_releng/build.sh**: No such file or directory
?
?
?
0
==> ERROR: A failure occurred in build().
    Aborting..._
    
    I've checked, there is a build.sh file, but it's empty. I'm completely lost 😞

**Comment by aunicorn111** [comment] 2023-03-06 05:47
Am I just left hanging? 😕

**Comment by Torxed** [comment] 2023-03-06 07:15
Not hanging, but life came in the way :)
I've ran this project through a fresh install and it appears working.

Do you mind providing the steps you took?
Because I sense that you might be running `makepkg` but this project doesn't have a PKGBUILD, so I'm wondering what's going on here.

For reference, here's a completely clean run from fresh setup to finish:
![screenshot](https://user-images.githubusercontent.com/861439/223042896-d25e5dc7-4be1-4951-afb8-c7be056772ae.png)

**Comment by aunicorn111** [comment] 2023-03-06 08:12
I understand and thank you for the reply!!
And yes, you are right, I did try to install the package via makepbk as in example right here https://wiki.archlinux.org/title/User:Torxed/Archiso_offline#Example_build_process 
Was I not supposed to do that?? 🙊

**Comment by Torxed** [comment] 2023-03-06 08:14
Aaah, sneaky! You found that documentation hehe.
That's my "private" documentation, it's not officially released (hence why it's under my username).

I haven't automated the AUR package in a while as I haven't set up an automatic build flow yet.
So you can safely ignore that page for now, or at least don't take it word for word yet :)

Closing this as everything appears to be working as intended.
And I'll make sure to fix the AUR package for `makepkg` in a while, but it's not a huge priority as it works as a python module first and foremost.

**Closed as completed by Torxed** 2023-03-06 08:14 UTC

**Comment by aunicorn111** [comment] 2023-03-06 08:16
I am having difficulties with installing archiso-offline itself 😅  Not with ISO building 😅 😅

**Comment by aunicorn111** [comment] 2023-03-06 08:16
OOOhhh!

**Comment by aunicorn111** [comment] 2023-03-06 08:17
Okay, thank you! Have a nice day :3

**Comment by Torxed** [comment] 2023-03-06 08:22
Hehe, no worries!
In the future this project will be installable, but until I sort out automatic building and deploying it will stay a Python lib/project hehe. Apologies for the confusion ^^

**Comment by aunicorn111** [comment] 2023-03-06 09:25
Sorry to bother again, but I got curious why do you have (main) in your path?:o I've never seen anything like this before

**Comment by Torxed** [comment] 2023-03-06 09:31
> Sorry to bother again, but I got curious why do you have (main) in your path?:o I've never seen anything like this before

GitHub default :) They changed it ~1 year ago in light of all the backlash on the internet. I can't be bothered so whatever is default I'll use hehe.

**Comment by aunicorn111** [comment] 2023-03-06 09:37
Oh thats cool!
